name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-workflow:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "✅"
          BRANCH_NAME: "test"
          IMAGES_FOLDER: "generated"
          GIT_USER_EMAIL: "dkj@somaiya.edu"
          GIT_USER_NAME: "Divya Jain"
